// Sample data
export const medications = [
    {
        id: 1,
        name: 'Aspirin',
        description:
            'Antibiotic used to treat various types of bacterial infections',
        manufacturer: 'WellnessPharma',
        price: 42.04,
    },
    {
        id: 2,
        name: 'Paracetamol',
        description: 'Used to treat high cholesterol',
        manufacturer: 'MedLife',
        price: 26.52,
    },
    {
        id: 3,
        name: 'Lisinopril',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'HealthPlus',
        price: 6.07,
    },
    {
        id: 4,
        name: 'Ciprofloxacin',
        description: 'Used to treat type 2 diabetes',
        manufacturer: 'PharmaCorp',
        price: 22.11,
    },
    {
        id: 5,
        name: 'Aspirin',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'PharmaGen',
        price: 14.53,
    },
    {
        id: 6,
        name: 'Ibuprofen',
        description: 'Used to treat high cholesterol and triglyceride levels',
        manufacturer: 'VitalCare',
        price: 31.98,
    },
    {
        id: 7,
        name: 'Ciprofloxacin',
        description: 'Antibiotic used to treat bacterial infections',
        manufacturer: 'MedLife',
        price: 36.87,
    },
    {
        id: 8,
        name: 'Omeprazole',
        description: 'Pain reliever and a fever reducer',
        manufacturer: 'MediPure',
        price: 33.72,
    },
    {
        id: 9,
        name: 'Lisinopril',
        description: 'Used to treat high cholesterol and triglyceride levels',
        manufacturer: 'MedLife',
        price: 20.99,
    },
    {
        id: 10,
        name: 'Atorvastatin',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'PharmaGen',
        price: 43.15,
    },
    {
        id: 11,
        name: 'Ibuprofen',
        description: 'Pain reliever and a fever reducer',
        manufacturer: 'GoodHealth',
        price: 49.08,
    },
    {
        id: 12,
        name: 'Paracetamol',
        description: 'Used to treat high cholesterol',
        manufacturer: 'HealthPlus',
        price: 40.03,
    },
    {
        id: 13,
        name: 'Amoxicillin',
        description: 'Used to treat high cholesterol and triglyceride levels',
        manufacturer: 'PharmaGen',
        price: 14.27,
    },
    {
        id: 14,
        name: 'Ciprofloxacin',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'PharmaCorp',
        price: 6.34,
    },
    {
        id: 15,
        name: 'Omeprazole',
        description: 'Pain reliever and a fever reducer',
        manufacturer: 'HealthPlus',
        price: 43.67,
    },
    {
        id: 16,
        name: 'Metformin',
        description: 'Pain reliever and a fever reducer',
        manufacturer: 'HealthPlus',
        price: 45.02,
    },
    {
        id: 17,
        name: 'Paracetamol',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'VitalCare',
        price: 43.25,
    },
    {
        id: 18,
        name: 'Paracetamol',
        description: 'Used to treat high cholesterol and triglyceride levels',
        manufacturer: 'MedLife',
        price: 37.55,
    },
    {
        id: 19,
        name: 'Aspirin',
        description: 'Used to treat high blood pressure',
        manufacturer: 'PharmaCorp',
        price: 37.83,
    },
    {
        id: 20,
        name: 'Omeprazole',
        description: 'Used to treat high cholesterol and triglyceride levels',
        manufacturer: 'PharmaGen',
        price: 24.21,
    },
    {
        id: 21,
        name: 'Amoxicillin',
        description: 'Used to treat gastroesophageal reflux disease',
        manufacturer: 'MediPure',
        price: 30.75,
    },
    {
        id: 22,
        name: 'Paracetamol',
        description:
            'Antibiotic used to treat various types of bacterial infections',
        manufacturer: 'CareMed',
        price: 33.21,
    },
    {
        id: 23,
        name: 'Aspirin',
        description: 'Used to treat high cholesterol and triglyceride levels',
        manufacturer: 'WellnessPharma',
        price: 34.79,
    },
    {
        id: 24,
        name: 'Amoxicillin',
        description: 'Nonsteroidal anti-inflammatory drug',
        manufacturer: 'CareMed',
        price: 9.55,
    },
    {
        id: 25,
        name: 'Metformin',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'PharmaGen',
        price: 8.37,
    },
    {
        id: 26,
        name: 'Paracetamol',
        description: 'Pain reliever and a fever reducer',
        manufacturer: 'WellnessPharma',
        price: 18.6,
    },
    {
        id: 27,
        name: 'Aspirin',
        description: 'Used to treat type 2 diabetes',
        manufacturer: 'WellnessPharma',
        price: 37.73,
    },
    {
        id: 28,
        name: 'Ibuprofen',
        description: 'Reduces pain, fever, or inflammation',
        manufacturer: 'CareMed',
        price: 16.67,
    },
    {
        id: 29,
        name: 'Ibuprofen',
        description: 'Used to treat type 2 diabetes',
        manufacturer: 'MedLife',
        price: 21.86,
    },
    {
        id: 30,
        name: 'Simvastatin',
        description:
            'Antibiotic used to treat various types of bacterial infections',
        manufacturer: 'MedLife',
        price: 27.02,
    },
    {
        id: 31,
        name: 'Metformin',
        description: 'Used to treat gastroesophageal reflux disease',
        manufacturer: 'WellnessPharma',
        price: 23.28,
    },
]
